config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "job_sites#index"
  get 'intro', to: 'static_pages#intro'
  get 'tips', to: 'static_pages#tips'
  get 'boolean', to: 'static_pages#boolean'
  get 'reports/per_site', to: 'reports#per_site'
  get 'reports/per_week', to: 'reports#per_week'
  get 'reports/per_campaign', to: 'reports#per_campaign'
  get 'reports/pathrise', to: 'reports#pathrise'

  resources :job_postings
  resources :email_opportunities
  
  resources :job_sites do
    resources :job_postings
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.applied_per_site
    return ApplicationRecord.connection.select_all("SELECT 
                s.name, COUNT(*) AS site_count 
            FROM job_sites s JOIN job_postings p ON p.job_site_id = s.id 
            GROUP BY p.job_site_id")
  end

  def self.applied_per_week
    return ApplicationRecord.connection.select_all("SELECT 
                STRFTIME('%Y', p.applied_at) || '/' || STRFTIME('%W', p.applied_at) AS week_name,
                STRFTIME('%Y', p.applied_at) AS year, 
                STRFTIME('%W', p.applied_at) AS week,
                STRFTIME('%m', p.applied_at) AS month,  
                COUNT(*) AS week_count
            FROM job_sites s JOIN job_postings p ON p.job_site_id = s.id 
            GROUP BY week_name
            ORDER BY year ASC, week ASC")
  end

  def self.applied_per_campaign
    return ApplicationRecord.connection.select_all("
            SELECT
                s.name AS search_site_name, 
                p.company_name, p.posting_title, p.posting_location_city, p.posting_location_type, 
                STRFTIME('%m-%d-%Y', p.applied_at) AS applied_on,
                STRFTIME('%m-%d-%Y', p.interviewed_at) AS interviewed_on,
                STRFTIME('%m-%d-%Y', p.rejected_at) AS rejected_on
            FROM job_postings p
            JOIN job_sites s ON p.job_site_id = s.id
            WHERE p.applied_at > '2024-01-01'")
  end

  def self.applied_pathrise
    return ApplicationRecord.connection.select_all("
            SELECT
                p.company_name, p.posting_title, p.posting_status,
                STRFTIME('%m-%d-%Y', p.applied_at) AS applied_on,
                STRFTIME('%m-%d-%Y', p.interviewed_at) AS interviewed_on,
                STRFTIME('%m-%d-%Y', p.rejected_at) AS rejected_on
            FROM job_postings p
            WHERE p.applied_at > '2024-07-20'")
  end
end

app/models/email_opportunity.rb
class EmailOpportunity < ApplicationRecord
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :job_site
end

app/models/job_site.rb
class JobSite < ApplicationRecord
    has_many :job_postings, dependent: :destroy
end

app/models/search_engine.rb
class SearchEngine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_opportunities_controller.rb
class EmailOpportunitiesController < ApplicationController
    def index
        @email_opportunities = EmailOpportunity.all
    end

    def new
        @email_opportunity = EmailOpportunity.new
    end

    def create 
        @email_opportunity = EmailOpportunity.new(email_opportunity_params)

        if @email_opportunity.save
            redirect_to action: "index"
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
        @email_opportunity = EmailOpportunity.find(params[:id])
    end

    def update
        @email_opportunity = EmailOpportunity.find(params[:id])
    
        if @email_opportunity.update(email_opportunity_params)
          redirect_to action: "index"
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @email_opportunity = EmailOpportunity.find(params[:id])
        @email_opportunity.destroy
    
        redirect_to root_path, status: :see_other
    end
    
    private
    def email_opportunity_params
        params.require(:email_opportunity).permit(:recruiter_name, :recruiter_company, :opportunity_status, :email_received_at, :job_title, :job_type,  :job_duration, :pay_rate,  :job_location_type, :job_location_city, :job_description)
    end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
    def index
        @job_postings = JobPosting.all
    end

    def show
        @job_posting = JobPosting.find(params[:id])
    end

    def create 
        @job_site = JobSite.find(params[:job_site_id])
        @job_posting = @job_site.job_postings.create(job_postings_params)
        redirect_to job_site_path(@job_site)
    end

    def edit
        @job_posting = JobPosting.find(params[:id])
    end

    def update
        @job_posting = JobPosting.find(params[:id])
    
        if @job_posting.update(job_postings_params)
          redirect_to job_site_path(@job_posting.job_site_id)
        else
          render :edit, status: :unprocessable_entity
        end
      end

    def destroy
        @job_site = JobSite.find(params[:job_site_id])
        @job_posting = @job_site.job_postings.find(params[:id])
        @job_posting.destroy
        redirect_to job_site_path(@job_site), status: :see_other
    end

    private
    def job_postings_params
        params.require(:job_posting).permit(:posting_title, :company_name, :posting_url,  :posting_status, :posting_location_city, :posting_location_type, :employment_type, :posting_id, :pay_range, :applied_at, :rejected_at, :interviewed_at, :archive, :technology_stack, :posting_comments)
    end

end

app/controllers/job_sites_controller.rb
class JobSitesController < ApplicationController
  def index
    @job_sites = JobSite.all
  end

  def show
    @job_site = JobSite.find(params[:id])
  end

  def new
    @job_site = JobSite.new
  end

  def create
    @job_site = JobSite.new(job_site_params)

    if @job_site.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @job_site = JobSite.find(params[:id])
  end

  def update
    @job_site = JobSite.find(params[:id])

    if @job_site.update(job_site_params)
      redirect_to @job_site
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job_site = JobSite.find(params[:id])
    @job_site.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def job_site_params
    params.require(:job_site).permit(:name, :url, :rating, :resume_format, :github_field, :project_site_field,  :last_visited_at, :resume_updated_at,  :description, :review_text)
  end
end

app/controllers/reports_controller.rb
# Note: Application Record in: /app/models/application_record.rb

class ReportsController < ApplicationController
  def per_week
    @reportData = ApplicationRecord.applied_per_week
  end

  def per_site
    @reportData = ApplicationRecord.applied_per_site
  end

  def per_campaign
    @reportData = ApplicationRecord.applied_per_campaign
  end

  def pathrise
    @reportData = ApplicationRecord.applied_pathrise
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def intro
    end

    def tips
    end

    def boolean
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_opportunities_helper.rb
module EmailOpportunitiesHelper
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/helpers/job_sites_helper.rb
module JobSitesHelper
end

app/helpers/per_campaign_reports_helper.rb
module PerCampaignReportsHelper
end

app/helpers/per_site_reports_helper.rb
module PerSiteReportsHelper
end

app/helpers/per_week_reports_helper.rb
module PerWeekReportsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/email_opportunities/_form.html.erb
<div class="container mt-2">
<%= form_with model: @email_opportunity do |form| %>
    <div class="row">
        <div class="col-md-6 col-lg-3 mt-3">
            <div class="input-group">
            <label class="input-group"><strong>Recruiter Name</strong></label>
            <%= form.text_field :recruiter_name , class:"form-control", :required => true %>
            </div>
        </div>
        <div class="col-md-6 col-lg-3 mt-3">
            <div class="input-group">
            <label class="input-group"><strong>Recruiter Company</strong></label>
            <%= form.text_field :recruiter_company , class:"form-control", :required => true %>
            </div>
        </div>
        <!--div class="col-sm-6 col-lg-2 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Sent Response?</strong></label>
                <%= form.select :responded , ['Not Selected', 'Yes', 'No'], {}, { :class => "form-control" } %>
            </div>
        </div-->
        <div class="col-md-6 col-lg-3 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Status</strong></label>
                <%= form.select :opportunity_status, ['4 - No Response', '3 - Rejected', '2 - Awaiting Feedback', '1 - Actively Engaged'],
                     {}, { :class => "form-control" } %>
            </div>
        </div>
        <div class="col-md-6 col-lg-3 mt-3">
            <div class="input-group">
            <label class="input-group"><strong>Email Received At</strong></label>
            <%= form.datetime_field :email_received_at , class:"form-control", :required => true %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Job Title</strong></label>
                <%= form.text_field :job_title , class:"form-control", :required => true %>
            </div>
        </div>
        <div class="col-sm-6 col-lg-2 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Employment Type</strong></label>
                <%= form.select :job_type, ['Contract', 'Full-time', 'Freelance'], {}, { :class => "form-control" } %>
            </div>
        </div>
        <div class="col-sm-6 col-lg-4 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Contract Duration</strong></label>
                <%= form.text_field :job_duration , class:"form-control", :required => true %>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Pay Rate</strong></label>
                <%= form.text_field :pay_rate , class:"form-control", :required => true %>
            </div>
        </div>
        <div class="col-sm-6 col-lg-2 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Location Type</strong></label>
                <%= form.select :job_location_type, ['On-Site', 'Hybrid', 'Remote'], {}, { :class => "form-control" } %>
            </div>
        </div>
        <div class="col-sm-6 col-lg-4 mt-3">
            <div class="input-group">
                <label class="input-group"><strong>Location City</strong></label>
                <%= form.text_field :job_location_city , class:"form-control", :required => true %>
            </div>
        </div>
    </div>


  <div class="row">
    <div class="col">
      <div class=" mb-3 mt-3 w3-padding w3-round ws-grey w3-border w3-padding-16">
        <label class="input-group"><strong>Job Description</strong></label>
        <%= form.text_area :job_description, class:"form-control", rows: 15, style:"margin-top:5px!important" %>
      </div>
    </div>
  </div>

  <%# <p>
    To Add:
    <ul>
      <li>Show the logo (and update new image)</li>
      <li>Active?</li>
    </ul>
  </p> %>

  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/email_opportunities/edit.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h3>Edit Email Opportunity</h3>
</div>

<%= render "form", email_opportunity: @email_opportunity %>

app/views/email_opportunities/index.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h1>Email Opportunities </h1>
</div>


<div class="container mt-5">
    <div class="row mb-4">
        <div class="col">
            <%= link_to "New Email Opportunity", new_email_opportunity_path, class:"btn btn-primary" %>
        </div>
    </div>
    <table id='email_opportunity_dt' class="table table-striped" style="width:100%">
        <thead>
            <th>Job Title</th>
            <th>Recruiter Name</th>
            <!--th>Job Type</th-->
            <th>Status</th>
            <th>Location Type</th>
            <th>City</th>
            <!--th>Pay Rate</th-->
            <th>Received On</th>
            <th>Action</th>
        </thead>

        <tbody>
        <% @email_opportunities.each do |email_opportunity| %>
        <tr>
            <td><%= email_opportunity.job_title %></td>
            <td><%= email_opportunity.recruiter_name %></td>
            <!--td><%= email_opportunity.job_type%></td--> 
            <td><%= email_opportunity.opportunity_status %></td>
            <td><%= email_opportunity.job_location_type %></td>
            <td><%= email_opportunity.job_location_city %></td>
            <!--td><%= email_opportunity.pay_rate %></td-->
            <td data-order="<%= unless email_opportunity.email_received_at.nil? 
              email_opportunity.email_received_at.strftime("%F %T") 
              end %>" >
              <%= unless email_opportunity.email_received_at.nil? 
              email_opportunity.email_received_at.strftime("%a %b %d, %Y %r") 
              end %></td>
            <td>
                <a href="/email_opportunities/<%= email_opportunity.id %>/edit">Edit</a>
                <%= link_to "Delete", [email_opportunity], data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                            } %>

            </td>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // JavaScript, NOT jquery... jquery not likely loaded yet!

  console.log("email_opportunities/index.html.js ready func")
      new DataTable('#email_opportunity_dt', {
        order: [[2, 'asc']],
        "pageLength": 25,
        "autoWidth": true
    });
});
</script>

app/views/email_opportunities/new.html.erb
<div class="container-fluid p-1 bg-success text-white text-center">
  <h1>New Email Opportunity</h1>
</div>

<%= render "form", email_opportunity: @email_opportunity %>

app/views/job_postings/_form.html.erb
<div class="container mt-5">
    <%= form_with model: [ @job_site, @job_site.job_postings.build ] do |form| %>
    <div class="row">
        
        <div class="col-3">
            <div class="input-group">
                <label class="input-group"><strong>Company Name</strong></label>
                <%= form.text_field :company_name , class:"form-control", :required => true %>
            </div>
        </div>
        <%= form.hidden_field :company_url, value: "" %>
        <div class="col-4">
            <div class="input-group">
                <label class="input-group"><strong>Posting Title</strong></label>
                <%= form.text_field :posting_title , class:"form-control", :required => true %>
            </div>
        </div>
        <%= form.hidden_field :posting_url, value: "" %>
        <div class="col-3">
            <div class="input-group">
                <label class="input-group"><strong>Location City</strong></label>
                <%= form.text_field :posting_location_city , class:"form-control", :required => true %>
            </div>
        </div>
        <div class="col-2">
            <div class="input-group">
                <label class="input-group"><strong>Location Type</strong></label>
                <%= form.select :posting_location_type, ['Remote', 'On-Site', 'Hybrid'], {}, { :class => "form-control" } %>
            </div>
        </div>
    </div>
    <%= form.hidden_field :employment_type, value: "" %>
    <%= form.hidden_field :posting_id, value: "" %>
    <%= form.hidden_field :pay_range, value: "" %>
    <%= form.hidden_field :applied_at, value: Time.current.getlocal %>
    <%= form.hidden_field :rejected_at, value: "" %>
    <%= form.hidden_field :archive, value: "" %>
    <%= form.hidden_field :technology_stack, value: "" %>
    <%= form.hidden_field :posting_comments, value: "" %>


    <div class="row">
        <div class="col-3">
            <%= form.submit %>
        </div>
    </div>
    <% end %>
</div>

<%# add archived, pay range, company logo %>

app/views/job_postings/_job_posting.html.erb
<% @job_site.job_postings.each do |job_posting| %>
  <% if job_posting.company_name.nil? 
        next
      end
  %>
  <tr>
    <td><%= job_posting.company_name %></td>
    <td><%= job_posting.posting_title %></td>
    <td><%= job_posting.posting_location_type %></td>
    <td><%= job_posting.posting_location_city %></td>
    <td data-order="<%= unless job_posting.applied_at.nil? 
              job_posting.applied_at.strftime("%F %T") 
              end %>" >
              <%= unless job_posting.applied_at.nil? 
              job_posting.applied_at.strftime("%a %b %d, %Y %r") 
              end %></td>
    <td>
    <a href="/job_postings/<%= job_posting.id %>/edit">Edit</a>
    <%= link_to "Delete", [job_posting.job_site, job_posting], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </td>
    
  </tr>
<% end %>

app/views/job_postings/index.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h1>Job Postings Applied </h1>
</div>


<div class="container mt-5">
    <table id='job_postings_dt' class="table table-striped" >
        <thead>
            <th>Company Name</th>
            <th>Posting Title</th>
            <!--th>Location Type</th-->
            <th>Posting Status</th>
            <!--th>Pay Range</th-->
            <th>Applied On</th>
            <th>Rejected On</th>
            <th>Interviewed On</th>
        </thead>

        <tbody>
        <% @job_postings.each do |job_posting| %>
        <tr>
          <td><%= link_to job_posting.company_name, job_posting %></td>
          <td><%= job_posting.posting_title %></td>
          <!--td><%= job_posting.posting_location_type %></td-->
          <td><%= job_posting.posting_status %></td>
          <!--td><%= job_posting.pay_range %></td-->
          <td data-order="<%= unless job_posting.applied_at.nil? 
              job_posting.applied_at.strftime("%F %T") 
              end %>" >
                <%= unless job_posting.applied_at.nil? 
                job_posting.applied_at.strftime("%b %d, %Y") 
                end %>
          </td>
          <td data-order="<%= unless job_posting.rejected_at.nil? 
              job_posting.rejected_at.strftime("%F %T") 
              end %>" >
                <%= unless job_posting.rejected_at.nil? 
                job_posting.rejected_at.strftime("%b %d, %Y") 
                end %>
          </td>
          <td data-order="<%= unless job_posting.interviewed_at.nil? 
              job_posting.interviewed_at.strftime("%F %T") 
              end %>" >
                <%= unless job_posting.interviewed_at.nil? 
                job_posting.interviewed_at.strftime("%b %d, %Y") 
                end %>
          </td>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // JavaScript, NOT jquery... jquery not likely loaded yet!
  console.log("Hello World!");
  console.log("index.js ready func")
      new DataTable('#job_postings_dt', {
        "autoWidth": false
    });
});
</script>

app/views/job_postings/show.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h3>Job Posting: <%= @job_posting.company_name %> <%= @job_posting.posting_title %></h3>


</div>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <%= link_to "Edit Posting", edit_job_posting_path(@job_posting), class:"btn btn-primary" %>
        </div>
    </div>

    <dl class="row mt-5">
        
        <dt class="col-sm-2"> Posting Title </dt>
        <dd class="col-sm-4"><%= @job_posting.posting_title %></dd>
        <dt class="col-sm-2"> Status </dt>
        <dd class="col-sm-4"><%= @job_posting.posting_status %></dd>

        <dt class="col-sm-2">Company Name</dt>
        <dd class="col-sm-4"><%= @job_posting.company_name %></dd>
        <dt class="col-sm-6">
        <dt class="col-sm-2"> Posting City </dt>
        <dd class="col-sm-4"><%= @job_posting.posting_location_city %></dd>
        <dt class="col-sm-2"> Location Type </dt>
        <dd class="col-sm-4"><%= @job_posting.posting_location_type %></dd>

        <dt class="col-sm-2"> Employment Type </dt>
        <dd class="col-sm-4"><%= @job_posting.employment_type %></dd>
        <dt class="col-sm-2"> Pay Range </dt>
        <dd class="col-sm-4"><%= @job_posting.pay_range %></dd>

        <dt class="col-sm-2"> Applied On </dt>
        <dd class="col-sm-4"><%= @job_posting.applied_at.strftime("%a %b %d, %Y %r") %></dd>
        <dt class="col-sm-2"> Rejected On </dt>
        <dd class="col-sm-4"><%= unless @job_posting.rejected_at.nil? 
                @job_posting.rejected_at.strftime("%a %b %d, %Y %r") 
                end %></dd>

        <dt class="col-sm-2"> Technology Stack </dt>
        <dd class="col-sm-10"><%= @job_posting.technology_stack %></dd>

        <dt class="col-sm-2"> Posting Comments </dt>
        <dd class="col-sm-10"><%= @job_posting.posting_comments %></dd>
    </dl>
</div>

app/views/job_sites/_form.html.erb
<div class="container mt-5">
<%= form_with model: @job_site do |form| %>
  <div class="row">
    <div class="col-5">
      <div class="input-group">
        <label class="input-group"><strong>Name</strong></label>
        <%= form.text_field :name , class:"form-control", :required => true %>
      </div>
    </div>
    <div class="col-5">
      <div class="input-group">
        <label class="input-group"><strong>URL</strong></label>
        <%= form.text_field :url , class:"form-control" %>
      </div>
    </div>
    <div class="col-2">
      <div class="input-group">
        <label class="input-group"><strong>Rating (1-20)</strong></label>
        <%= form.number_field :rating , in: 1..20, 
                class:"form-control", :required => true %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-2">
      <div class="input-group">
          <label class="input-group"><strong>Resume Format</strong></label>
          <%= form.select :resume_format , ['Builder Only', 'PDF Only', 'Both'] %>
      </div>
    </div>
    <div class="col-4">
      <div class="input-group form-check">
        <%= form.check_box :github_field , class:"form-check-input" %>
        <%= form.label :github_field , " Has Git Hub Field", class:"form-check-label fw-bolder" %>
      </div>
      <div class="input-group form-check">
        <%= form.check_box :project_site_field , class:"form-check-input"  %>
        <%= form.label :project_site_field , " Has Project Site Field", class:"form-check-label" %>
      </div>
    </div>


    <div class="col-3">
      <div class="input-group">
        <label class="input-group"><strong>Last Visited</strong></label>
        <%= form.date_field :last_visited_at , class:"form-control", :required => true %>
      </div>
    </div>
    <div class="col-3">
      <div class="input-group">
        <label class="input-group"><strong>Resume Updated</strong></label>
        <%= form.date_field :resume_updated_at , class:"form-control", :required => true %>
      </div>
    </div>
  </div>


<div class="row">
    <div class="col">
      <div class=" mb-3 mt-3 w3-padding w3-round ws-grey w3-border w3-padding-16">
        <label class="input-group"><strong>Review Headline</strong></label>
        <%= form.text_area :review_text, class:"form-control", rows: 1, style:"margin-top:5px!important" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class=" mb-3 mt-3 w3-padding w3-round ws-grey w3-border w3-padding-16">
        <label class="input-group"><strong>Review Details</strong></label>
        <%= form.text_area :description, class:"form-control", rows: 10, style:"margin-top:5px!important" %>
      </div>
    </div>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/job_sites/edit.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h3>Edit Job Site: <%= @job_site.name %></h3>
</div>

<%= render "form", job_site: @job_site %>

app/views/job_sites/index.html.erb
<div class="container-fluid p-1 bg-primary text-white text-center">
  <h1>Job Search Sites </h1>
</div>


<div class="container mt-5">
    <div class="row mb-4">
        <div class="col">
            <%= link_to "New Job Site", new_job_site_path, class:"btn btn-primary" %>
        </div>
    </div>
    <table id='job_site_dt' class="table table-striped" style="width:100%">
        <thead>
            <th>Site Name</th>
            <th>Site URL</th>
            <th>Rating</th>
            <th>Review Headline</th>
            <th>Site Last Visted</th>
        </thead>

        <tbody>
        <% @job_sites.each do |job_site| %>
        <tr>
            <td><%= link_to job_site.name, job_site %></td>
            <td><%= job_site.url %></td>
            <td><%= job_site.rating %></td>
            <td><%= job_site.review_text %></td>
            <td data-order="<%= unless job_site.last_visited_at.nil? 
              job_site.last_visited_at.strftime("%F %T") 
              end %>"><%= job_site.last_visited_at.strftime("%a %b %d, %Y")  %></td>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // JavaScript, NOT jquery... jquery not likely loaded yet!

  console.log("job_sites/index.html.js ready func")
      new DataTable('#job_site_dt', {
        order: [[2, 'asc']],
        "pageLength": 25
    });
});
</script>

app/views/job_sites/new.html.erb
<div class="container-fluid p-1 bg-success text-white text-center">
  <h1>New Job Site</h1>
</div>

<%= render "form", job_site: @job_site %>

app/views/job_sites/show.html.erb
<div class="container-fluid p-1 bg-primary sticky-top text-white text-center">
<h3><%= @job_site.name %></h3>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <%= link_to "Edit Site", edit_job_site_path(@job_site), class:"btn btn-primary" %>
      <%= link_to "Destroy", job_site_path(@job_site), class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <strong>URL</strong><br>
      <a href="<%= @job_site.url %>"> <%= @job_site.url %></a>
    </div>
    <div class="col">
      <strong>Rating</strong><br>
      <%= @job_site.rating %>
    </div>
    <div class="col">
      <strong>Last Visited</strong><br>
      <%= @job_site.last_visited_at.strftime("%a %b %d, %Y") %>
    </div>
    <div class="col">
      <strong>Resume Last Updated</strong><br>
      <%= @job_site.resume_updated_at.strftime("%a %b %d, %Y") %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col">
    <strong>Review Headline</strong>: <%= @job_site.review_text %>       
    </div>
  </div>
  
  <br>
  <div class="row">
    <div class="col">
      <strong>Review Details</strong><br>
      <%= @job_site.description %>
    </div>
  </div>

  
</div>

<div class="container mt-5">
<h2 style='width:100%'>Add a Job Posting 
  <button onclick="scrollToBottom()" class="btn btn-secondary mx-9 px-9" style="float:right">Scroll To Bottom</button></h2>
  <%= render 'job_postings/form' %>
</div>

<div class="container mt-5">
  <h2>Job Postings Applied</h2>
  <table id='postings_dt' class="table table-striped" style="width:100%">
        <thead>
            <th>Company Name</th>
            <th>Posting Title</th>
            <th>Posting Type</th>
            <th>Posting City</th>
            <th>Applied On</th>
            <th>Actions</th>
        </thead>

        <% unless @job_site.job_postings.nil? %>
        <tbody>

          <%= render 'job_postings/job_posting' %>

        </tbody>
        <% end %>
    </table>


</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // JavaScript, NOT jquery... jquery not likely loaded yet!
  console.log("job_sites/show.html.js ready func")
      new DataTable('#postings_dt', {
        order: [[4, 'desc']]
  });

  // $("body").bind("DOMSubtreeModified", function() {
  //   alert("tree changed");
  // });   // executes when the SEARCH box is used.  But not before then.
});

function scrollToBottom() { 
    window.scrollTo(0, document.body.scrollHeight)
} 
</script>